- src/omnicore/rpc.cpp
- src/omnicore/rpctx.cpp
- src/omnicore/sp.h
- src/omnicore/tx.cpp
- test/config.ini
Saving data on db , and retrieve information related to high/low prices since last update block (data can be check using tl_getproperty rpc for now).
> few changes on rpc data retrieval

- src/omnicore/tx.cpp
- test/config.ini
> New labels added

- src/omnicore/rpc.cpp
- test/config.ini
> New rpcs for oracle and native contracts info

- src/omnicore/errors.h
- src/omnicore/log.cpp
- src/omnicore/log.h
- src/omnicore/omnicore.h
- src/omnicore/tx.cpp
- test/config.ini
> Error numbers added

- src/omnicore/omnicore.h
- test/config.ini
> Perpetuals added

- src/omnicore/rules.cpp
- src/omnicore/tx.cpp
- test/config.ini
> IsTransactionTypeAllowed restiction added

- src/omnicore/log.cpp
- src/omnicore/log.h
- src/omnicore/omnicore.cpp
- src/omnicore/script.cpp
- src/omnicore/wallettxs.cpp
- test/config.ini
> Few changes on fees

- src/omnicore/rpc.cpp
- src/omnicore/rpctxobject.cpp
- src/omnicore/rpctxobject.h
- src/omnicore/tx.cpp
- src/omnicore/tx.h
- src/rpc/client.cpp
- test/config.ini
Fix  #110 . All details of any transaction in the block.
> Getalltxforblock

- src/omnicore/rules.cpp
- test/config.ini
The mistake was found on rules.cpp (the transaction create oracle contracts wasn't in the vector of restrictions).
Also, the tests are showing we solve the litecoin feees bug, after some modifications on wallettxs.cpp : this solve #91.
> Few mistakes solved. Litecoin fees working

- src/omnicore/omnicore.cpp
- src/omnicore/omnicore.h
- test/config.ini
> block creation fixed in vesting tokens

- src/rpc/client.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- test/config.ini
> dcurrency total rpc added

- src/tradelayer/tradelayer.cpp
- test/config.ini
> issue fixed

- src/tradelayer/consensushash.cpp
- src/tradelayer/dex.cpp
- src/tradelayer/mdex.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/tally.h
- src/tradelayer/test/tally_tests.cpp
- src/tradelayer/test/x_trade_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- test/config.ini
> token count

- src/rpc/client.cpp
- src/tradelayer/createpayload.cpp
- src/tradelayer/createpayload.h
- src/tradelayer/globals.cpp
- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/mdex.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/sp.h
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
- test/config.ini
> Mark price

- src/chainparams.cpp
- src/consensus/consensus.h
- src/consensus/params.h
- src/pow.cpp
In order to work in the public testnet (we want to delete the branch normal).
> Adding public testnet params

- src/tradelayer/tradelayer.cpp
error found using server stage.
> print error fixed

- src/tradelayer/rules.cpp
- test/config.ini
In order to have control over this transaction we need this change.
> vesting tokens restrictions added

- src/tradelayer/rules.cpp
- src/tradelayer/tx.cpp
- test/config.ini
check needed after update_tally_map functions
> sender balance check added

- src/tradelayer/rules.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/tradelayer.cpp
- test/config.ini
If the amount from vesting sometimes is very small we need to avoid using asserts with update_tally_map function.
> few changes for vesting tokens

- src/tradelayer/rpc.cpp
- src/tradelayer/rpctx.cpp
> listoracles rpc fixed

- src/tradelayer/tx.cpp
in order to have perpetual swap working
> perpetual swap logic math fixed

- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/rpcrequirements.h
- src/tradelayer/rpctx.cpp
> collateral requirement in contract traded fixed

- src/tradelayer/mdex.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/tx.cpp
changes: interpret logic part and a few lines in logic math function
> Cancel contract orders fixed

- src/Makefile.tradelayertest.include
- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/test/requirements_tests.cpp
- src/tradelayer/tx.cpp
> few changes in margin requirement

- src/tradelayer/log.cpp
- src/tradelayer/rpctx.cpp
> rpc vector fixed

- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/rpcrequirements.h
- src/tradelayer/rpctx.cpp
Requirements logic fixed in order to reserve the correct amount of collateral.
Fix #177
> some requirements changes

- src/rpc/client.cpp
- src/tradelayer/rpcpayload.cpp
Payloads for:
- Change admin address on Oracle
- Create Oracle
- Publish Oracle Data
- Close Out Oracle
- Create KYC registrar
- Change admin on KYC registrar
> new rpcpayloads

- src/tradelayer/mdex.cpp
- src/tradelayer/rpc.cpp
- test/config.ini
> getcache rpc fixed

- src/tradelayer/mdex.cpp
- src/tradelayer/mdex.h
- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/rpcrequirements.h
- src/tradelayer/rpctx.cpp
> tl_closeposition fixed

- src/rpc/client.cpp
- src/tradelayer/rpc.cpp
> tl_getposition fixed

- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
@Galuf1 : this is the patch in order to fix last issue, and the tl_listkyc is added in order to watch all information reladed a kyc registers.
> listkyc added, kyc check fixed

- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/mdex.cpp
- src/tradelayer/mdex.h
- src/tradelayer/rpctx.cpp
- src/tradelayer/sp.h
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
First functions to buy ALLs in mdex  using cache. Also kyc fixed (for @Galuf1  testing)
> fee-caching functions added, kyc functions fixed

- src/tradelayer/tradelayer.cpp
With this changes we have ALLs supply in the admin address (just for testing).
> Alls supply

- src/rpc/client.cpp
- src/tradelayer/mdex.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
feeCacheBuy update and small fix for kyc system
> Fee caching

- src/initial_conditions.h
- src/tradelayer/globals.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/sp.h
> tl_getmax_peggedcurrency fixed

- src/bitcoind.cpp
- src/tradelayer/dex.cpp
- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/mdex.cpp
- src/tradelayer/mdex.h
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
> LTC volume 

- src/tradelayer/tradelayer.cpp
The actual code contains a new VestingTokens function with updates in order to avoid errors in divisions. If LTC volume is 0 there's nothing to update into vesting addresses (tally maps).
This fix #194 . Also there's another few small changes related with order in the code.
> VestingTokens function updated

- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/tx.cpp
Cleaning the code and a few more fixs.
> few more fixs

- src/tradelayer/rpcpayload.cpp
sendvestingtoken rpc (for payload) deleted.
> rpc deleted

- src/tradelayer/rpcpayload.cpp
- test/functional/tl_payloads.py
> Attestation rpcpayload

- src/tradelayer/rpcpayload.cpp
> help message updated in attestation rpcpayload

- src/tradelayer/createpayload.cpp
- src/tradelayer/createpayload.h
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
- test/functional/tl_payloads.py
> small changes

- src/tradelayer/dex.cpp
- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/mdex.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
> improvements

- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
Small changes to  pass by reference some variables.
> code improvements (part 2)

- src/Makefile.tradelayertest.include
- src/tradelayer/createpayload.cpp
- src/tradelayer/createpayload.h
- src/tradelayer/rpc.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/rpcvalues.cpp
- src/tradelayer/test/create_payload_tests.cpp
- src/tradelayer/test/functions_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_basics.py
more changes in order to improve the code
> code improvements

- src/Makefile.tradelayertest.include
- src/tradelayer/mdex.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/test/contractdex_tests.cpp
> edgeorderbook function changes, unit test added

- src/tradelayer/dex.cpp
- src/tradelayer/dex.h
- src/tradelayer/errors.h
- src/tradelayer/fetchwallettx.cpp
- src/tradelayer/log.cpp
- src/tradelayer/mdex.cpp
- src/tradelayer/persistence.cpp
- src/tradelayer/persistence.h
- src/tradelayer/rpc.cpp
- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/rpctxobject.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- src/tradelayer/utilsbitcoin.cpp
- src/tradelayer/walletcache.cpp
- src/tradelayer/wallettxs.cpp
I've found calling settlement and expiration code acting in mastercore_handler_tx. Which means, this code is executed each new transaction ! . The solution was just put the code into mastercore_handler_block_begin. Now those functions are called just 1 time each block. Other changes was made for NULL pointers. This changes passed all functional tests.
> function called from right place, and some nullptr optimizations

- src/tradelayer/dex.cpp
- src/tradelayer/mdex.cpp
- src/tradelayer/rpcvalues.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/wallettxs.cpp
- src/tradelayer/wallettxs.h
more changes related with improvements/optimization and technical debt.
> technical debt, improvements

- src/rpc/client.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/sp.h
> new rpc added

- src/tradelayer/mdex.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/rpcrequirements.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
> technical debt, improvements (part 8)

- src/rpc/client.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/sp.h
- test/functional/tl_natives.py
changes in the argument in order to accept the name of contract.
> changes in argument of rpc

- src/tradelayer/createpayload.cpp
- src/tradelayer/dex.cpp
- src/tradelayer/mdex.cpp
> technical debt, improvements (part 9)

- src/tradelayer/rpctx.cpp
- src/tradelayer/test/create_payload_tests.cpp
- src/tradelayer/test/uint256_extensions_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- test/functional/tl_basics.py
payloads unit tests and uint256 arith tests updated. Changes in core included (related with the return of  logic_math, also some assert() functions added)
> unit tests updated

- src/tradelayer/mdex.cpp
- src/tradelayer/mdex.h
- src/tradelayer/rpc.cpp
- test/functional/tl_natives.py
- test/functional/tl_oracles.py
> open interes rpc

- src/tradelayer/createpayload.cpp
- src/tradelayer/createpayload.h
- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/mdex.cpp
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/rpcvalues.cpp
- src/tradelayer/rpcvalues.h
- src/tradelayer/sp.h
- src/tradelayer/test/create_payload_tests.cpp
- src/tradelayer/test/requirements_tests.cpp
- src/tradelayer/test/uint256_extensions_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.h
- test/functional/tl_payloads.py
> upgrading margin requirement size and few other changes

- src/rpc/client.cpp
- src/tradelayer/activation.cpp
- src/tradelayer/rules.cpp
- src/tradelayer/rules.h
- src/tradelayer/tradelayer.cpp
- test/functional/tl_activation.py
Activation and deactivation rpctxs working in regtest and testnet, it Fix #287. We need to include more features in the list in the future.
> Activation test

- src/Makefile.tradelayertest.include
- src/rpc/client.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpctx.cpp
- src/tradelayer/rpcvalues.cpp
- src/tradelayer/rpcvalues.h
- src/tradelayer/rules.cpp
- src/tradelayer/test/rpcvalues_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
- test/functional/tl_activation.py
- test/functional/tl_payloads.py
- test/functional/tl_rpcvalues.py
This Pull Request fix issue linked.
> Contract input

- src/tradelayer/rpc.cpp
- test/functional/tl_list.py
Verbose option added. Of course, these aren't all changes required in #305. I'm just updating development branch in order to acelerate the work flow.
> list properties update

- src/tradelayer/dex.cpp
> few improvements in dex

- src/rpc/client.cpp
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpctx.cpp
This PR solve #312 @patrickdugan
> commit and withdraw payloads added

- src/coins.h
- src/tradelayer/rpcrawtx.cpp
This PR solves #318. All functional tests passed.
> decode rpc fixed

- test/functional/tl_reorg.py
Basic chain reorg  added. In the future we should add more reorg test, with different scenarios in order to see how all internal states are changing.
> reorg basic tests added

- src/tradelayer/consensushash.cpp
- src/tradelayer/mdex.cpp
- src/tradelayer/mdex.h
- src/tradelayer/rpc.cpp
- src/tradelayer/test/checkpoint_tests.cpp
- src/tradelayer/test/persistence_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
- test/functional/tl_tradechannels.py
Some refactoring (new class added), and other changes related.
> refactoring tradechannels

- src/tradelayer/test/persistence_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_persistence.py
Few improvements, unit tests updated.
> updating development

- src/tradelayer/test/persistence_tests.cpp
> persistence unit test updated

- src/tradelayer/rpc.cpp
> fHelp: add in for some rpc functions.

- src/tradelayer/rpctxobject.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_activation.py
This solve requirements of #343.
> information of tx invalidation added

- src/tradelayer/errors.h
- src/tradelayer/tradelayer.cpp
Saving and integer instead of a string in database.
> improvements  in tx details

- src/tradelayer/rpcvalues.cpp
> ParseArray updated

- src/tradelayer/activation.cpp
- src/tradelayer/rules.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- src/validation.cpp
- src/validation.h
Fill in some Abort node and Warnings.
Is this the right logic? What do you think?
> Add in DoAbortNode, DoWarning.

- src/tradelayer/rpc.cpp
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpcrawtx.cpp
- src/tradelayer/rpctx.cpp
Using fHelp flag in a better way into the IF args.
> fHelp flag improvement

- src/tradelayer/test/vesting_tests.cpp
> small changes on vesting unit test

- src/tinyformat.h
* Last update was in 2017.
* for details see BTC commit 978b25528c5f336e0aade73bd1b320500f257f70
> util: Update tinyformat to upstream

- src/Makefile.am
- src/Makefile.tradelayer.include
- src/rpc/register.h
- src/tradelayer/wallettxs.cpp
This makes the build complete with --disable-wallet.
> build: --disable-wallet fix.

- src/tradelayer/mdex.cpp
- src/tradelayer/rpctxobject.cpp
- src/tradelayer/test/contractdex_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_vesting.py
> extended ids and some enum types added

- src/Makefile.am
- src/bech32.cpp
- src/bech32.h
- src/txdb.cpp
- src/util/vector.h
- src/wallet/wallet.cpp
* fixes one header file with missing guards.
> bech32: update -> latest upstream.

- src/Makefile.am
- src/span.h
Used for some updates to come.
> Add Slice: a (pointer, size) array view that acts like a container

- src/Makefile.am
- src/attributes.h
- src/httpserver.cpp
- src/init.cpp
- src/test/scrypt_tests.cpp
- src/test/util_tests.cpp
- src/util/strencodings.cpp
- src/util/strencodings.h
- src/util/string.cpp
- src/util/string.h
- src/util/system.cpp
- src/util/system.h
- src/util/threadnames.cpp
- src/util/threadnames.h
- src/validation.cpp
* add in threadnames.
* add in string.
* add in attributes.
* few other changes to make those work.
Needed for some upcoming updates.
> Add in a few util bits.

- configure.ac
- src/Makefile.am
- src/bench/Examples.cpp
- src/bitcoin-cli.cpp
- src/bitcoind.cpp
- src/httprpc.cpp
- src/init.cpp
- src/net.cpp
- src/policy/fees.cpp
- src/qt/paymentserver.cpp
- src/test/checkqueue_tests.cpp
- src/test/util_tests.cpp
- src/test/validation_block_tests.cpp
- src/tradelayer/rpc.cpp
- src/tradelayer/sp.cpp
- src/tradelayer/test/lock_tests.cpp
- src/tradelayer/tradelayer.cpp
- src/util/system.cpp
- src/util/time.cpp
- src/util/time.h
- src/validation.cpp
- src/wallet/db.cpp
- src/wallet/rpcdump.cpp
Required for some later updates.
Also fixed some tests .... tests are probably still in bad shape.
> util/time: bring up to date with upstream.

- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_rawtransactions.py
> fees added

- configure.ac
- src/fs.cpp
- src/fs.h
- src/init.cpp
- src/qt/guiutil.cpp
- src/test/scheduler_tests.cpp
- src/tradelayer/convert.cpp
- src/tradelayer/convert.h
- src/tradelayer/log.cpp
- src/tradelayer/persistence.cpp
- src/tradelayer/persistence.h
- src/tradelayer/sp.cpp
- src/tradelayer/sp.h
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/util/system.cpp
- src/util/system.h
- src/wallet/init.cpp
- src/wallet/rpcdump.cpp
* fs multibyte fixes for Windows.
* drop some useless includes.
* fix config file open on macOS;
https://github.com/bitcoin/bitcoin/pull/16044
* drop some useless functions.
* sync some logging functions with btc master.
* boost::filesystem::path -> fs::path
* fs - multibyte Windows path fixes.
Configure ---
* opt-in boost_progress.
* remove some dead boost workarounds.
* require boost 1.58.0.
> Various changes ---

- src/tradelayer/tradelayer.cpp
> boost-foreach: drop useless include.

- src/tradelayer/activation.cpp
- src/tradelayer/dex.cpp
- src/tradelayer/log.cpp
- src/tradelayer/rules.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/wallettxs.cpp
The fix at the end wasn't related with persistence, it was a format issue on progressReporter class. Other small fix and updates are also included. Everything was tested on testnet.
> Testnet fix

- src/tradelayer/rpcpayload.cpp
> Vesting fix

- src/tradelayer/rpc.cpp
- src/tradelayer/rpcpayload.cpp
- src/tradelayer/rpcrawtx.cpp
- src/tradelayer/rpctx.cpp
> rpcs info updated

- src/rpc/client.cpp
- src/tradelayer/rpcrawtx.cpp
- src/tradelayer/rpctxobject.cpp
- test/functional/tl_rawtransactions.py
- test/functional/tl_tradechannels.py
Hey @patrickdugan, this PR fix the rpc that you needed month before.
> tl_decodetransaction rpc update

- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/rpctxobject.cpp
- src/tradelayer/tradelayer.cpp
few update:  txobject functions and log.
> Tx info and log

- src/tradelayer/activation.cpp
activation address and vesting tokens issuer updated.
> addresses updated

- src/tradelayer/activation.cpp
- src/tradelayer/tradelayer.cpp
tl marker , activation address and vesting admin address updated.
> few changes 

- src/tradelayer/tx.cpp
> printtolog fix

- src/tradelayer/rules.cpp
> blocks updated

- src/tradelayer/tx.cpp
balance check to avoid crash in testnet
>  balance check updated

- src/tradelayer/tx.cpp
cleaning code ( deleting variables without use)
> cleaning code

- src/tradelayer/log.cpp
- src/tradelayer/log.h
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- test/functional/tl_remaining.py
> bug in instant trade fixed

- src/tradelayer/rpcrawtx.cpp
- src/tradelayer/rpcvalues.cpp
- test/functional/tl_tradechannels_change.py
> change address functional test added

- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tx.cpp
- test/functional/tl_tradechannels.py
- test/functional/tl_tradechannels_change.py
- test/functional/tl_tradechannels_expiration.py
Simplification of tradechannel's logic (balances in tallys). Few changes in functional tests
> tradechannels logic updated

- test/functional/tl_payloads.py
> transfer payload updated

- src/tradelayer/tradelayer.cpp
this looks nicer I think and less prone to mistakes while playing with pointers.
> TLMarker: simplify the code a bit.

- src/tradelayer/rules.cpp
Refactor the GetRestrictions() function a bit to avoid the array sizing.
> Refactor GetRestrictions().

- src/httpserver.cpp
- src/qt/bitcoingui.cpp
- src/qt/clientmodel.cpp
- src/qt/splashscreen.cpp
- src/qt/transactiontablemodel.cpp
- src/qt/walletmodel.cpp
- src/validation.cpp
- src/validationinterface.cpp
this is needed on my machine, bitrot fix
> fix some boost bind includes

- src/rpc/client.cpp
this fixes a simple parameter issue....
> tl_listproperties should take a bool.

- src/tradelayer/rpc.cpp
Hi! Here is the initial version of tl_getwalletbalance, please if someone could test it!
Additionally I cleaned up some formatting, I have more cleanup changes that I split up for another PR.
> Initial tl_getwalletbalance

- src/tradelayer/createpayload.cpp
The number is not yet allocated. XXX
> Add a method ManySend that encodes multiple sends.

- src/tradelayer/sp.h
- src/tradelayer/tx.cpp
Instead of the long list of returns we can make a data table and look through it.
This has the advantage that we can add more fields later on.
> Clean up strTransactionType a bit.

- src/tradelayer/mdex.cpp
- src/tradelayer/tradelayer.cpp
- test/functional/tl_oracle_self.py
Valentine found that trading against yourself can leave the orders in the orderbook. Which is undesirable and produce wrong sorting in prices too. This PR solves the issue.
> orderbook bug fixed

- contrib/install_db4.sh
This updates a contrib script I use to build db4, that unfortunately stopped working.
> installdb4: update for checksums.

- src/tradelayer/tx.cpp
> kyc for receivers added

- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_nodereward.py
This Pull Request contains all new changes required for node reward, tested on regtest
> Node reward blocks

- src/rpc/client.cpp
- src/tradelayer/createpayload.cpp
- src/tradelayer/createpayload.h
- src/tradelayer/errors.h
- src/tradelayer/rpctx.cpp
- src/tradelayer/rules.cpp
- src/tradelayer/rules.h
- src/tradelayer/tradelayer.h
- src/tradelayer/tx.cpp
- src/tradelayer/tx.h
Moving to master, we need just settlement structures (insurance), that are in branch settlement-02
> donation tx 

- src/tradelayer/mdex.cpp
- src/tradelayer/register.cpp
- src/tradelayer/register.h
- src/tradelayer/rpc.cpp
- src/tradelayer/tradelayer.cpp
- src/tradelayer/tradelayer.h
- test/functional/tl_oracles.py
PNL and UPNL working, settlement function working on regtest. @patrickdugan can you review these changes? Valentine can integrate it with the api. Any bug discovered will be fixed ASAP.
> Futures contracts and block settlement changes
